### ISSUE TITLE
2020.1 EAP1 Support

### ISSUE THREAD

**Issue by sergey-tihon** [gilday/dark-mode-sync-plugin#12] opened 2020-02-28 17:05 UTC
Thank you for the nice plugin @gilday 
Can you please release version that is compatible with 2020.1 EAP1

> The macOS Dark Mode Sync (id=com.github.gilday.darkmode, path=~/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-1/201.5616.21/Rider EAP.app.plugins/dark-mode-sync-plugin, version=1.1.0) plugin is incompatible (target build range is 192 to 193.*).

<img width="449" alt="image" src="https://user-images.githubusercontent.com/1197905/75569146-a1bdf900-5a65-11ea-99b4-ced21a45d449.png">

**Comment by kannicht** [comment] 2020-02-29 00:25
I'd recommend to hold a new release till the final release of the 2020.1 versions in April. 

Jetbrains might change things internally till then so we only require to implement changes once.

**Comment by gilday** [comment] 2020-02-29 19:20
@sergey-tihon because there is an unfortunate amount of manual testing (that I have not figured out how to automate) involved with releasing this plugin, I have decided not to support EAP releases. It's too much to keep up with. I will make sure to release a new version when 2020.1 graduates from EAP at which time I will close this issue.

**Comment by sergey-tihon** [comment] 2020-02-29 19:22
ok, but I thought that it should as easy as easy as change one number in target build range

**Comment by gilday** [comment] 2020-02-29 19:29
Yes, the code change is usually that easy. Testing to make sure it actually works is the hard part.

**Comment by Sottti** [comment] 2020-03-25 19:37
Is this the reason is not working on AS 4.0?

**Comment by stevesfdc** [comment] 2020-04-08 17:35
Any update on this?  2020.1 is now officially out...

**Comment by kannicht** [comment] 2020-04-09 22:51
Hi @stevesfdc ,

yeah, it's finally out. I just started to have a look at the things and I'm glad they haven't changed much. 

Even though, as @gilday said, it will take some days (I will try to make it work by the end of the easter weekend).

**Comment by gilday** [comment] 2020-04-09 23:03
Time to work on this is especially hard to come by these days with COVID-19 in the world and the changes it brings. Big thanks to @kannicht for helping out, you're the best

**Comment by kannicht** [comment] 2020-04-10 12:10
Quick progress update:

I already implemented the necessary changes and can confirm, that for now it is working inside IntelliJ 2020.1 on macOS.

There are more tests to go on both macOS and Windows 10.

**Comment by kannicht** [comment] 2020-04-10 20:52
Final update:

Just opened PR #15.

**Comment by gilday** [comment] 2020-04-11 16:22
It seems Travis CI is undergoing some maintenance at the moment. This will get shipped when Travis is ready to build the `master` branch

**Comment by kannicht** [comment] 2020-04-11 16:41
Awesome :)

Good job @gilday 

Greetings from Germany and stay safe :)

**Comment by gilday** [comment] 2020-04-13 11:20
JetBrains rejected the release due to compatibility problems

> Hello,
>
> Thank you for submitting the update.
> 
> The update of your plugin has some compatibility issues with IDEs versions below 201. It makes sense  to limit the 'since' version. You can do this in the plugin.xml file for the future versions of this plugin and on the update pages for the current.
>
> Please let me know as soon as the version has been changed so I will approve the update.
> I will be waiting for your answer.

I don't know what the compatibility problems are. Since I'm not interested in supporting legacy versions of IDEA anyway, I have bumped the minimum platform to version 201 in the plugin.xml. Perhaps these incompatibilities are the cause of the `NoClassDefFoundError`s in #13 🤷‍♂️

Re-releasing today 🤞

**Comment by kannicht** [comment] 2020-04-14 01:32
Already released and updatable from the IDE :)

**Comment by stevesfdc** [comment] 2020-04-14 01:58
> Already released and updatable from the IDE :)

Awesome!! Thanks for such a quick turnaround!

**Comment by gilday** [comment] 2020-04-15 17:29
Odd. I'm still getting the 

> The plugin update is pending JetBrains approval

On the [plugin page](https://plugins.jetbrains.com/plugin/12515-dark-mode-sync) and no update available in the IDE ☹️

**Comment by kannicht** [comment] 2020-04-15 19:49
Ist states pending, but the version history ist already updated.

**Closed as completed** 2020-04-16 15:12 UTC
Labels: enhancement

**Comment by gilday** [comment] 2020-04-19 17:43
Looks like it's available now 🎉

fwiw, I'd like to approach the next EAP differently. It might make sense to put out a release candidate version for EAP just to let folks test it out. EAP users have already agreed to use not-yet-stable software, so I don't think this is unreasonable.
