### ISSUE TITLE
When switching to a dark theme, not all elements change the scheme

### ISSUE THREAD

**Issue by BorzdeG** [gilday/dark-mode-sync-plugin#22] opened 2020-07-22 20:04 UTC
when manually changing the theme is no such problem

<img width="99" alt="image" src="https://user-images.githubusercontent.com/2332528/88222946-6a97f080-cc6f-11ea-9e77-4c0d740078b2.png">
<img width="267" alt="image" src="https://user-images.githubusercontent.com/2332528/88223003-7daac080-cc6f-11ea-8ce0-31c0cbd77451.png">
<img width="256" alt="image" src="https://user-images.githubusercontent.com/2332528/88224315-78e70c00-cc71-11ea-84e1-25f629894086.png">

**Comment by gilday** [comment] 2020-08-06 02:00
Duplicate of #18

**Closed as completed** 2020-08-06 02:01 UTC
